name: Unit Tests

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  run-tests:
    runs-on: windows-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Run unit tests
      working-directory: Portfolio.Tests
      run: dotnet test -v n
